name: Build and Run
on: push
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: File Permissions
        run: sudo chown -R 1000:1000 .
      - name: Build
        run: docker-compose run --rm composer install
      - name: Run
        run: docker-compose run --rm aoc aoc:all